### PR TITLE
changed TDE frame to use the standard DAQEth header

### PR DESCRIPTION
**Pull request by glehmannmiotto**

### CODE REVIEW

**Comment by bieryAtFnal** [comment]
In testing these changes, and the associated ones in the `fdreadoutlibs` and `rawdatautils` repos,  I saw crashes in the readout app.

This happened both with the `daq-systemtest/readout_type_scan` integtest and with a test in which I created the config input files by hand.

The problem seems to happen in the `SourceEmulatorModel::run_produce()` method around the location of the `memcpy`.  I wonder if the emulated data file that we fetch from the "assets" system needs to be updated to the new format?

Here are copies of the daqconf.json and dro_map.json files that I used:
```
(dbt) [biery@mu2edaq13 rundir]$ cat daqconf5.json 
{
  "boot": {
    "use_connectivity_service": true,
    "start_connectivity_service": true,
    "connectivity_service_host": "localhost",
    "connectivity_service_port": 15432
  },
  "readout": {
    "clock_speed_hz": 62500000,
    "data_rate_slowdown_factor": 1,
    "use_fake_cards": true,
    "default_data_file": "asset://?label=TDE16&subsystem=readout"
  },
  "trigger": {
    "trigger_window_before_ticks": 1000,
    "trigger_window_after_ticks": 1000,
    "trigger_rate_hz": 1.0
  }
}
(dbt) [biery@mu2edaq13 rundir]$ cat dro_map_tde.json 
[
    {
        "src_id": 100,
        "geo_id": {
            "det_id": 11,
            "crate_id": 1,
            "slot_id": 0,
            "stream_id": 0
        },
        "kind": "flx",
        "parameters": {
            "protocol": "full",
            "mode": "fix_rate",
            "host": "localhost",
            "card": 0,
            "slr": 0,
            "link": 0
        }
    },
    {
        "src_id": 101,
        "geo_id": {
            "det_id": 11,
            "crate_id": 1,
            "slot_id": 0,
            "stream_id": 1
        },
        "kind": "flx",
        "parameters": {
            "protocol": "full",
            "mode": "fix_rate",
            "host": "localhost",
            "card": 0,
            "slr": 0,
            "link": 1
        }
    }
]
```

**Comment by glehmannmiotto** [comment]
I committed a fix to fdreadoutlibs that should fix the issue. Please note that the readout map file you are using needs to be modified as there is only 1 link for each slot in TDE.

**Comment by bieryAtFnal** [comment]
So, I just need to change the slot number for source_id 101 to be non-zero?

Like this?

```
    {
        "src_id": 101,
        "geo_id": {
            "det_id": 11,
            "crate_id": 1,
            "slot_id": 1,   # changed zero to one here
            "stream_id": 1
        },
        "kind": "flx",
        "parameters": {
            "protocol": "full",
            "mode": "fix_rate",
            "host": "localhost",
            "card": 0,
            "slr": 0,
            "link": 1
        }
    }
```

Thanks!

**Comment by glehmannmiotto** [comment]
yes, that should be it.

**Review by bieryAtFnal — APPROVED** [review]
I'm now able to successfully run tests, so this looks good to me.

**Pull request merged**
